import type { Metadata } from "next";
import { auth } from "@/auth.config";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  const session = await auth();

  if ( session?.user ) {
    redirect('/');
  }

  return (
    <main className="w-screen min-h-screen p-9">
      { children }
    </main>
  );
}
