import { PaisEstadoCiudad } from "./pais_estado_ciudad_type";


const JSON_COUINTRIES_STATES_CITIES = "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/countries%2Bstates%2Bcities.json"


// Generated by https://quicktype.io


export const getData = async (url: string = JSON_COUINTRIES_STATES_CITIES) => { 
  const data: PaisEstadoCiudad[] = await fetch(url)
    .then(response => response.json())
  return data
}

//TODO: Implementar si se optione la API key para usarlo.
export const getPaisesVAPI = async () => {
  
  var headers = new Headers();
  headers.append("X-CSCAPI-KEY", "API_KEY");

  const requestOptions = {
    method: 'GET',
    headers: headers,
    //redirect: 'follow' // Set the redirect property to 'follow'
  };

  const data = fetch("https://api.countrystatecity.in/v1/countries", requestOptions)
    .then(response => response.json())
  
  return data

}

export const getPaises = async () => { 
  const data = await getData()
  return data.map((pais) => {
    return {
      id: pais.id.toString(),
      nombre: pais.name
    }
  })
}

export const getEstadosPorPais = async (name:string) => { 
  const data = await getData()
  return data.find((pais) => pais.name.toString() === name)
    ?.states.map((estado) => {
    return {
      id: estado.id.toString(),
      nombre: estado.name
    }
  })
}

export const getCiudadesPorEstado = async (nombrePais: string, nombreEstado: string) => { 
  const data = await getData()
  return data.find((pais) => pais.name.toString() === nombrePais)
    ?.states.find((estado) => estado.name.toString() === nombreEstado)
    ?.cities.map((ciudad) => {
    return {
      id: ciudad.id.toString(),
      nombre: ciudad.name
    }
  })
}
