import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { auth } from '@/auth.config';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  
  const session = await auth();
  if ( session?.user ) {
    redirect('/');
  }
 
  return (
    <div>
        { children }
    </div>
  );
}
